# Artificial Neural Network

### Importing the libraries

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


## Part 1 - Data Preprocessing

### Importing the dataset

In [0]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [0]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [0]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [0]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [0]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [0]:
print(X)

[[ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167  0.97024255
   0.02188649]
 [-1.00280393 -0.57873591  1.74273971 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
  -1.07636976]]


### Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
print(len(X_train), len(X_test), len(y_train), len(y_test))

8000 2000 8000 2000


## Part 2 - Building the ANN

### Importing packages

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense

### Initializing the ANN

In [0]:
classifier = Sequential()

### Adding the input layer and the first hidden layer

In [0]:
classifier.add(Dense(units =6, activation = 'relu'))

### Adding the second hidden layer

In [0]:
classifier.add(Dense(units =6, activation = 'relu'))

### Adding the output layer

In [0]:
classifier.add(Dense(units =1, activation = 'sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [0]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'] )

### Training the ANN on the Training set

In [0]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.5184 - accuracy: 0.7778
Epoch 2/100
8000/8000 [==============================] - 1s 100us/step - loss: 0.4329 - accuracy: 0.8112
Epoch 3/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.4118 - accuracy: 0.8199
Epoch 4/100
8000/8000 [==============================] - 1s 98us/step - loss: 0.3958 - accuracy: 0.8310
Epoch 5/100
8000/8000 [==============================] - 1s 99us/step - loss: 0.3782 - accuracy: 0.8391
Epoch 6/100
8000/8000 [==============================] - 1s 99us/step - loss: 0.3621 - accuracy: 0.8521
Epoch 7/100
8000/8000 [==============================] - 1s 97us/step - loss: 0.3538 - accuracy: 0.8559
Epoch 8/100
8000/8000 [==============================] - 1s 98us/step - loss: 0.3487 - accuracy: 0.8586
Epoch 9/100
8000/8000 [==============================] - 1s 100us/step - loss: 0.3452 - accuracy: 0.8593
Epoch 10/100
8000/8000 [==============================] - 1s

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [0]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5 )
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


### Making the Confusion Matrix

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1502   93]
 [ 197  208]]
